export const ActionTypes = {
  SET_FASALO: "SET_FASALO",
  SET_XISOOYIN: "SET_XISOOYIN",
  SET_MAADOOYIN: "SET_MAADOOYIN",
  SET_MACALIMIIN: "SET_MACALIMIIN",
  SET_NEW_PERIODS: "SET_NEW_PERIODS",
  SELECTED_FASAL: "SELECTED_FASAL",
  REMOVE_SELECTED_FASAL: "REMOVE_SELECTED_FASAL",
};
